spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:qa} #perfil por defecto

---

spring:
  #config:
    #activate:
     #on-profile: qa
  #datasource:
   # url: ${SPRING_DATASOURCE_URL_QA}
    #username: ${DB_QA_USER}
    #password: ${DB_QA_PASSWORD}
    #driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://supermarket_db_dev:3306/supermarket_dev
    username: admin
    password: 1998
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://supermarket_db_prod:3306/supermarket_prod
    username: admin
    password: 1998
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false