services:
  supermarketapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    restart: always
    depends_on:
      - supermarket_db_qa
      - supermarket_db_dev
      - supermarket_db_prod

  supermarket_db_dev:
    image: mariadb:10.11
    container_name: db-dev
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_DEV_ROOT_PASSWORD:-1998}
      MARIADB_DATABASE: ${DB_DEV_NAME:-supermarket_dev}
      MARIADB_USER: ${DB_DEV_USER:-admin_dev}
      MARIADB_PASSWORD: ${DB_DEV_PASSWORD:-1998}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_DEV_USER}", "-p${DB_DEV_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 3

  supermarket_db_qa:
    image: mariadb:10.11
    container_name: db-qa
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_QA_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_QA_NAME}
      MARIADB_USER: ${DB_QA_USER}
      MARIADB_PASSWORD: ${DB_QA_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data_qa:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_QA_USER}", "-p${DB_QA_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 3

  supermarket_db_prod:
    image: mariadb:10.11
    container_name: db-prod
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PROD_ROOT_PASSWORD:-1998}
      MARIADB_DATABASE: ${DB_PROD_NAME:-supermarket_prod}
      MARIADB_USER: ${DB_PROD_USER:-admin_prod}
      MARIADB_PASSWORD: ${DB_PROD_PASSWORD:-1998}
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data_prod:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_PROD_USER}", "-p${DB_PROD_PASSWORD}" ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data_dev:
  mariadb_data_prod:
  mariadb_data_qa:
